name: aapkaparking
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  carousel_slider: ^4.2.1
  firebase_auth: ^5.1.3
  pinput: ^5.0.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  video_player: ^2.9.1
  lottie: ^3.1.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.3.1
  qr_flutter: ^4.1.0
  cached_network_image: 3.3.1
  intl: ^0.19.0
  mobile_scanner: ^5.1.1
  esc_pos_utils: ^1.1.0
  flutter_blue_plus: ^1.32.12
  blue_thermal_printer: ^1.2.3
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  
 
  
  

dependency_overrides:
  image: ^3.0.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    
    - assets/animations/
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/aapka logo.webp"
  